import 'package:flutter/material.dart';
import 'package:radik_project/Theme.dart';

List<Text> TimePar = <Text>[
  Text('8:10\n9:45', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('9:55\n11:30', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('11:40\n-\n13:15', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('13:35\n15:10', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('15:20\n16:55', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('17:05\n18:40', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('18:50\n20:15', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];

List<Text> Monday = <Text>[
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('Англ.', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('АПиД', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('Тер.Вер.', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];
List<Text> Tuesday = <Text>[
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('СЦТ', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ТРПП', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('Теория Вероятностей Математическая статистика.', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('Физ-ра', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];
List<Text> Wednesday = <Text>[
  Text('ПБД', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('АПиД', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];
List<Text> Thursday = <Text>[
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ТРПП', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('АКМС', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];
List<Text> Friday = <Text>[
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ПИТОН', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];
List<Text> Saturday = <Text>[
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];
List<Text> Sunday = <Text>[
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('--', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];

List<Text> MondayTypePar = <Text>[
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ПР', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ПР', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ПР', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];
List<Text> TuesdayTypePar = <Text>[
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ПР', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ПР', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ЛК', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ПР', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];
List<Text> WednesdayTypePar = <Text>[
  Text('ПР', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ЛК', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];
List<Text> ThursdayTypePar = <Text>[
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ЛК', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ПР', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];
List<Text> FridayTypePar = <Text>[
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('ЛК', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('-', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];
List<Text> SaturdayTypePar = <Text>[
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];
List<Text> SundayTypePar = <Text>[
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
  Text('', style: TextStyle(fontSize: 15, color: MainTheme[4]),
      textAlign: TextAlign.center),
];



